[rank0]: Traceback (most recent call last):
[rank0]:   File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/autoexpl/xqb/gen_guess_llama_split.py", line 191, in <module>
[rank0]:     main(args)
[rank0]:   File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/autoexpl/xqb/gen_guess_llama_split.py", line 156, in main
[rank0]:     qanta_json = fileio.load_singlefile_w_prefix(qanta_filename)
[rank0]:   File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/autoexpl/tools/fileio.py", line 16, in load_singlefile_w_prefix
[rank0]:     raise FileNotFoundError
[rank0]: FileNotFoundError
[rank0]:[W330 14:23:37.334524958 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
E0330 14:23:42.109103 61385 .venv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 61389) of binary: /fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/bin/python3.9
Traceback (most recent call last):
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/lib/python3.9/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/lib/python3.9/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/.venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/fs/clip-projects/qest/eloirghi/automatic_explicitation_LLM/autoexpl/xqb/gen_guess_llama_split.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-30_14:23:42
  host      : gammagpu04.umiacs.umd.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 61389)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
